# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas', models.TextField()),
                ('version', models.PositiveSmallIntegerField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=200)),
                ('os_family', models.CharField(max_length=200)),
                ('browser_family', models.CharField(max_length=200)),
                ('is_mobile', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='canvas',
            name='computer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authc.Computer'),
        ),
    ]
